version: "3.2"
services:
    redis:
        container_name: redis
        image: redis:3.2.11
    api:
        container_name: website-data
        build:
            context: ./api
            dockerfile: Dockerfile
        links:
            - db
        ports:
            - "5000:5000"
        volumes:
            - ./api/:/code
        entrypoint: watchmedo auto-restart --recursive --pattern="*.py" --directory="." ./docker_entrypoint.sh
        depends_on:
            - redis
    db:
        image: mysql:5.7
        ports:
            - "32000:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./db-data:/var/lib/mysql

        