version: "3.2"
services:
    redis:
        container_name: redis
        image: redis:3.2.11
        ports:
            - "6379:6379"
    api:
        container_name: website_data_dev
        build:
            context: .
            dockerfile: Dockerfile
        links:
            - db
        ports:
            - "5000:5000"
        volumes:
            - ./:/code
        entrypoint: watchmedo auto-restart --recursive --pattern="*.py" --directory="." ./docker_entrypoint.sh
        depends_on:
            - redis
    db:
        container_name: mysql-db
        image: mysql:5.7
        ports:
            - "32000:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ../db-data:/var/lib/mysql

        